[project]
name = "babymonitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.14.3",
    "fastapi>=0.140.13",
    "mediapipe>=0.10.35",
    "opencv-python>=4.13.0.92",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "streamlit>=1.60.0",
    "tqdm>=4.70.0",
    "uvicorn>=0.51.0",
]
